[package]
name = "tinystate"
keywords = ["dfa", "fsm", "automata", "state-machine"]
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
exclude.workspace = true

[workspace]
members = ["derive"]

[workspace.package]
version = "1.1.0"
edition = "2024"
authors = ["Saverio Scagnoli <svscagn@gmail.com>"]
description = "Fast and tiny finite state machine"
documentation = "https://docs.rs/tinystate"
repository = "https://github.com/saverioscagnoli/tinystate"
homepage = "https://github.com/saverioscagnoli/tinystate"
license = "MIT"
readme = "README.md"
exclude = [".gitignore", "assets", "CHANGELOG.md"]

[dependencies]
tinystate-derive = { path = "derive", version = "1.1.0", optional = true }

[dev-dependencies]
tinystate = { path = ".", features = ["derive"] }

[features]
default = []
derive = ["dep:tinystate-derive"]
