[package]
name = "tinystate-derive"
description = "Derive macros for tinystate"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

keywords = ["dfa", "fsm", "automata", "state-machine", "derive"]

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.5"

[lib]
proc-macro = true
